#version: '2'
services:
  sce-printer:
    container_name: sce-printer-dev
    build:
      context: .
      dockerfile: ./printer/Dockerfile.dev
    ports:
      # we use port 14000 as that is what the website expects
      # the printing server to be running on
      - 14000:14000
    volumes:
      - ./config:/app/config
      - ./printer:/app/printer
      - ./tmp:/tmp
    command:
      - --development
      - --port=14000
      - --dont-delete-pdfs
  snmp-collector:
    build:
      context: .
      dockerfile: ./collector/Dockerfile
    ports:
      - 5000:5000
    
