#version: '2'
services:
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile
    privileged: true
    restart: "no"
    volumes:
      - ./config/config.json:/tmp/config.json  # Add this line
      - ~/.ssh/id_ed25519-tunnel.pub:/app/ssh_key.pub
      - ~/.ssh/id_ed25519-tunnel:/app/ssh_key
      - ~/.ssh/known_hosts:/app/known_hosts
      - "/etc/cups/ppd/:/etc/cups/ppd"
    tty: true
  snmp-collector:
    build:
      context: .
      dockerfile: ./collector/Dockerfile
# we attach the print container to an external docker
# network called "poweredge". we do this so a prometheus
# container can pull metrics from the server over HTTP
# and relay the metrics to a Grafana dashboard.
networks:
  default:
    external:
      name: poweredge
